# Generated by Django 3.2.16 on 2023-06-26 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro_his_paciente',
            name='CNV',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploadcsv.data_cnv'),
        ),
    ]
