# Generated by Django 3.2.16 on 2023-06-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0002_maestro_his_paciente_cnv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_cnv',
            name='CNV',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
