# Generated by Django 3.2.16 on 2023-07-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0004_remove_maestro_his_paciente_cnv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_cnv',
            old_name='Malfcongénita',
            new_name='Malfcongenita',
        ),
        migrations.RenameField(
            model_name='data_cnv',
            old_name='Perímetrocefálico',
            new_name='Perimetrocefalico',
        ),
        migrations.RenameField(
            model_name='data_cnv',
            old_name='Profesión',
            new_name='Profesion',
        ),
        migrations.RenameField(
            model_name='data_cnv',
            old_name='Teléfono',
            new_name='Telefono',
        ),
        migrations.RemoveField(
            model_name='data_cnv',
            name='Perímetrotorácico',
        ),
        migrations.AddField(
            model_name='data_cnv',
            name='Perimetrotoracico',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
